// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig, env } from "prisma/config";

// Load environment-specific .env file
// Default to .env, but can be overridden with NODE_ENV
const envFile = process.env.NODE_ENV === 'development' ? '.env.dev' : '.env';
config({ path: envFile });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("TOURNAMENT_DATABASE_URL"),
  },
});
